# Generated by Django 4.2.4 on 2023-08-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('custom_add_product', 'Can add product'), ('custom_edit_product', 'Can edit product'), ('custom_delete_product', 'Can delete product')]},
        ),
    ]
