# Generated by Django 4.2.4 on 2023-08-31 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0005_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
