# Generated by Django 4.2.4 on 2023-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0007_product_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1),
        ),
    ]
